services:
  - type: web_service
    name: Acharya Zodiac Calculator Backend
    env: python
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
  - type: static_site
    name: Acharya Zodiac Calculator Frontend
    env: static
    branch: main
    root: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: ""
